### ISSUE TITLE
When logging to the web version using form, user is redirected to hub/

### ISSUE THREAD

**Issue by mattash** [surp-hovhannes/bahk#12]
Ideally the user should be redirected to the hub/web route after logging on since that's were they begin the process. This is referencing "feature/user-login" branch #6

**Comment by andylitalo** [comment]
Agreed! This can be fixed by changing the login redirect url [here](https://github.com/surp-hovhannes/bahk/blob/feature/user-login/bahk/settings.py#L148). I'll make the change.

**Comment by andylitalo** [comment]
This is resolved in the outstanding `feature/user-login` PR in [this line](https://github.com/surp-hovhannes/bahk/pull/6/files#diff-3d7c9cff5931eeecbd6f03cd21ba54a22514e216bf6492fa57b0502e6b9d52d9R157)
