### ISSUE TITLE
Wednesday fast currently showing "None until None"

### ISSUE THREAD

**Issue by andylitalo** [surp-hovhannes/bahk#25]
![Live and Pray](https://github.com/surp-hovhannes/bahk/assets/13158190/22049787-675a-493f-8f42-b8fa7fb87e9f)

**Comment by mattash** [comment]
Makes sense. There is no culmination feast. We can test for that and show nothing if it's None. 

Wondering if there is  something else meaningful to show. Number of Wednesdays/Fridays left in the year?

**Comment by andylitalo** [comment]
I created [a branch](https://github.com/surp-hovhannes/bahk/tree/bugfix/countdown-not-showing-for-wed-fri-fasts) that just removes the countdown on those days and it seems okay. A countdown of the number of W/F left also sounds good!
