### ISSUE TITLE
Allow user to click on fast card image to open "Read More" modal with fast description

### ISSUE THREAD

**Issue by andylitalo** [surp-hovhannes/bahk#26]
Vague attempt at this [here](https://github.com/surp-hovhannes/bahk/tree/feature/click-fast-card-opens-modal)

**Comment by mattash** [comment]
@andylitalo I worked on this a little and its in a working state. I'm pushing the branch with a PR.

**Comment by andylitalo** [comment]
I'm going to close this since it's working well enough on staging.
