### ISSUE TITLE
Password Encryption

### ISSUE THREAD

**Issue by andylitalo** [surp-hovhannes/bahk#46]
Passwords are stored unencrypted. This is a security concern. Noted by schanna

**Comment by mattash** [comment]
Is that true? I haven't looked into this but the admin section of the site says they are encrypted ![image](https://github.com/user-attachments/assets/f3f10da1-dd29-4ee6-beb6-7b2ffdc64d04)

**Comment by andylitalo** [comment]
Oh, interesting! I neglected to check. Stephen mentioned it, so I'll ask him to clarify.
