### ISSUE TITLE
Duplicate Fast Days

### ISSUE THREAD

**Issue by mattash** [surp-hovhannes/bahk#8]
![Screenshot 2024-05-07 at 12 03 42 PM](https://github.com/surp-hovhannes/bahk/assets/133799/7b0037ac-b3b0-42d2-bf57-efd367ced35f)

It's possible to add duplicate dates for the same fast. I can see that this might affect data integrity in the future. We should add some validation logic to the model that will prevent this.

A quick AI chat suggests modifying models.py like this maybe? 

```
class Day(models.Model):
    """Model for a day in time."""
    date = models.DateField()
    fasts = models.ManyToManyField(Fast, related_name="days")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['date', 'fasts'], name='unique_day_fast')
        ]

    def __str__(self):
        return self.date.strftime("%B-%d-%Y")
```

**Comment by andylitalo** [comment]
Thanks for catching and documenting the bug. The immediate problem can be resolved by making the `date` field unique (`unique=True`). Django will only allow one reference from a fast to a date.

Just submitted a PR to address this.

**Comment by mattash** [comment]
This is closed, yeah?

**Comment by andylitalo** [comment]
Yep! I'll close it.
